env: dev
app:
  name: "Essay Grader from YAML"
  version: "2.0.0"
  debug: true
  log_level: "INFO"

semantic:
  model_name: "all-MiniLM-L6-v2"
  chunk_size: 256
  overlap: 32
  batch_size: 16
  device: "cpu"

spacy_config:
  model_name: "en_core_web_md"
  batch_size: 16
  device: "cpu"
